### ISSUE TITLE
Error in Fetch instruments

### ISSUE THREAD

**Issue by sakibgit** [sreenivasdoosa/sdoosa-algo-trade-python#29]
C:\Users\vin\AppData\Local\Microsoft\WindowsApps\python3.9.exe D:/aaa/sdoosa-algo-trade-python-master/src/main.py
Deploy  Directory = D:/temp/python-deploy
LogFile Directory = D:/temp/python-deploy/logs
 * Serving Flask app 'main' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Deploy  Directory = D:/temp/python-deploy
LogFile Directory = D:/temp/python-deploy/logs
Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "D:\aaa\sdoosa-algo-trade-python-master\src\core\Algo.py", line 26, in startAlgo
    Instruments.fetchInstruments()
  File "D:\aaa\sdoosa-algo-trade-python-master\src\instruments\Instruments.py", line 75, in fetchInstruments
    instrumentsList = Instruments.loadInstruments()
  File "D:\aaa\sdoosa-algo-trade-python-master\src\instruments\Instruments.py", line 41, in loadInstruments
    instruments = json.loads(isdFile.read())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 866003 column 5 (char 20569415)

Process finished with exit code 0

**Comment by sakibgit** [comment]
issue solved by deleting instruments.json from deploy directory
